require 'plugins.guess-indent'
require 'plugins.mini'
require 'plugins.telescope'
require 'plugins.lspconfig'
require 'plugins.lensline'
require 'plugins.conform'
require 'plugins.blink-cmp'
require 'plugins.treesitter'
require 'plugins.debug'
require 'plugins.indent_line'
require 'plugins.lint'
require 'plugins.harpoon'
require 'plugins.neogit'
require 'plugins.snacks'
require 'plugins.themery'
require 'plugins.yazi'
require 'plugins.oil'
require 'plugins.go'
require 'plugins.fff'
require 'plugins.ts-context'
require 'plugins.easy-dotnet'
require 'plugins.flutter-tools'

-- vim: ts=2 sts=2 sw=2 et
